// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NfcReader.Backend.Contexts;

#nullable disable

namespace NfcReader.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124123219_Rename-Col-InTab-Recording_and_Add-Tab-ClockingType")]
    partial class RenameColInTabRecording_and_AddTabClockingType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NfcReader.Backend.Models.ClockingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OID");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("T_CLOCKING_TYPE", (string)null);
                });

            modelBuilder.Entity("NfcReader.Backend.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("OID");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OIDDEPARTEMENT");

                    b.Property<string>("Names")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOMS");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OIDFONCTION");

                    b.Property<string>("StaffId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MATRICULE");

                    b.Property<string>("Surnames")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRENOMS");

                    b.HasKey("Id");

                    b.ToTable("T_EMPLOYE", (string)null);
                });

            modelBuilder.Entity("NfcReader.Backend.Models.RawClocking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OID");

                    b.Property<string>("BadgeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BADGEID");

                    b.Property<DateTime>("ClockingTime")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE_HEURE_POINTAGE");

                    b.Property<Guid>("ClockingTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OID_TYPE_POINTAGE");

                    b.Property<DateTime>("Created")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED");

                    b.Property<string>("StaffId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OID_EMPLOYE");

                    b.HasKey("Id");

                    b.HasIndex("ClockingTypeId");

                    b.ToTable("T_POINTAGE_TRAV_MOBILE", (string)null);
                });

            modelBuilder.Entity("NfcReader.Backend.Models.Recording", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("OID");

                    b.Property<string>("BadgeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BADGE_ID");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STAFF_ID");

                    b.HasKey("Id");

                    b.ToTable("T_MOBILE_BADGE_INFO", (string)null);
                });

            modelBuilder.Entity("NfcReader.Backend.Models.RawClocking", b =>
                {
                    b.HasOne("NfcReader.Backend.Models.ClockingType", null)
                        .WithMany("RawClockings")
                        .HasForeignKey("ClockingTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_RawClocking_ClockingType");
                });

            modelBuilder.Entity("NfcReader.Backend.Models.ClockingType", b =>
                {
                    b.Navigation("RawClockings");
                });
#pragma warning restore 612, 618
        }
    }
}
