// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NfcReader.Backend.Contexts;

#nullable disable

namespace NfcReader.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NfcReader.Backend.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("OID");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IDDEPARTEMENT");

                    b.Property<string>("Names")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOMS");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OIDFONCTION");

                    b.Property<string>("StaffId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MATRICULE");

                    b.Property<string>("Surnames")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRENOMS");

                    b.Property<string>("badgeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BADGEID");

                    b.HasKey("Id");

                    b.ToTable("T_EMPLOYE", (string)null);
                });

            modelBuilder.Entity("NfcReader.Backend.Models.RawClocking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OID");

                    b.Property<string>("BadgeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BADGEID");

                    b.Property<DateTime>("ClockingTime")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE_HEURE_POINTAGE");

                    b.Property<DateTime>("Created")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED");

                    b.Property<string>("StaffId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OID_EMPLOYE");

                    b.HasKey("Id");

                    b.ToTable("T_POINTAGE_TRAV_MOBILE", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
